vich_uploader:
    db_driver: orm

    mappings:
        sound_thumbnail:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
        sound_sound:
            uri_prefix: /mp3/sounds
            upload_destination: '%kernel.project_dir%/public/mp3/sounds'
